
participants:
  - el_type: geth
    cl_type: lighthouse
    cl_image: docker.io/giobbe/poc-lighthouse
    count: 2


network_params:
  network_id: "585858"

# Point the package at our *custom* genesis generator (built with our SSZ)
ethereum_genesis_generator_params:
  image: docker.io/giobbe/poc-ethereum-genesis-generator
  extra_env: {TEE_VENDOR: 2}

additional_services:
  - dora
