participants:
- el_type: geth
  cl_type: lighthouse
  cl_image: docker.io/giobbe/pote-lighthouse-amd64
  validator_count: 1
  count: 3
  cl_extra_env_vars:
    RUST_LOG: info,lighthouse=debug,eth2_network_config=info
  cl_devices:
  - /dev/tpm0
  ethereum_metrics_exporter_enabled: true
  prometheus_config:
    scrape_interval: 5s
    labels:
      role: validator-node
      network: pote-devnet
network_params:
  network_id: '585858'
  gas_limit: 30000000
  seconds_per_slot: 6
  additional_preloaded_contracts: "{\n  \"0x1000000000000000000000000000000000000001\": {\n    \"balance\": \"100000000000000000000000\",\n    \"comment\": \"Test account 1 (100K ETH)\"\n  },\n  \"0x2000000000000000000000000000000000000002\": {\n    \"balance\": \"100000000000000000000000\",\n    \"comment\": \"Test account 2 (100K ETH)\"\n  },\n  \"0x3000000000000000000000000000000000000003\": {\n    \"balance\": \"50000000000000000000000\",\n    \"comment\": \"Test account 3 (50K ETH)\"\n  }\n}\n"
ethereum_genesis_generator_params:
  image: docker.io/giobbe/pote-ethereum-genesis-generator-amd64
  extra_env: {}
additional_services:
- dora
dora_params:
  image: docker.io/giobbe/pote-dora-amd64
